app:
  directory:
    input: "/data/in"
    output: "/data/out"
  file:
    extension: ".dat"

logging:
  level:
    org.springframework.web: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} - [%-5level] [%t] %c{1} - %msg%n"

spring:
  application:
    name: sales-analysis